language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g
  - gulp build

after_script:
  - cd ./public
  - git init
  - git config user.name "jasonlee529"
  - git config user.email "libo529@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - git push --force --quiet "https://${GH_TOKEN}@${GH_ESSAY_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
     - GH_REF: github.com/jasonlee529/jasonlee529.github.io.git
     - GH_ESSAY_REF: github.com/jasonlee529/essay.git
